# Usamos uma imagem oficial do Node.js baseada em Alpine Linux (leve e estável)
FROM node:20-alpine

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia o package.json e o lock para instalar as dependências
COPY package*.json ./

# Instala as dependências dentro do contêiner
RUN npm install

# Copia todo o resto do seu código para dentro do contêiner
COPY . .

# Expõe a porta que o Vite usa para que possamos acessá-la de fora
EXPOSE 5173

# O comando que será executado quando o contêiner iniciar
CMD ["npm", "run", "dev"]